admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
